### ISSUE TITLE
支持更多AI

### ISSUE THREAD

**Issue by chenweiask** [YunYouJun/ai-sfc#5]
### Clear and concise description of the problem

OpenAI的API虽然不贵，但依旧需要一些费用，而且ChatGPT对中文的支持没有国内AI好。

### Suggested solution

支持讯飞星火、百度文心一言、Google Gemini等其他AI语言模型

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Helmsman-Lab** [comment]
openai is all your need

**Comment by YunYouJun** [comment]
目前使用的 DeepSeek 有 1000万 token 的免费额度，与 OpenAI API 兼容。

目前只计划适配兼容 OpenAI API 的大模型。

**Comment by YunYouJun** [comment]
```bash
# .env
# Use DeepSeek
AI_SERVICE_URL='https://api.deepseek.com/v1'
MODEL_NAME='deepseek-chat'
# you can get free tokens from https://platform.deepseek.com/
OPENAI_API_KEY=your_deepseek_api_key
```
